stages:
  - unit-test
  - acceptance-test
  - deploy

unit-test:
  image: node:latest
  stage: unit-test
  script:
    - npm i
    - npm test
   

acceptance-test:
  image: cypress/browsers:node16.14.0-slim-chrome99-ff97
  stage: acceptance-test
  script:
    - npm i
    - npm run cypress:run

deplloy:
  image: node:latest
  stage: deploy
  script:
    - cd serverless
    - npm install -g serverless
    - serverless deploy --aws-profile default 
  environment:
    name: staging
    url: https://localhost:3000  