stages:
  - unit-test
  - acceptance-test
  - deploy

unit-test:
  image: node:latest
  stage: unit-test
  script:
    - npm i
    - npm test
   

acceptance-test:
  image: cypress/browsers:node16.14.0-slim-chrome99-ff97
  stage: acceptance-test
  script:
    - npm i
    - export CYPRESS_HOST=http://localhost:3000
    - npm start & npx wait-on $CYPRESS_HOST
    - npm run cypress:run

deplloy:
  image: node:latest
  stage: deploy
  script:
    - npm i
    - npm run build
    - cd serverless
    - npm install -g serverless
    - serverless client deploy --no-confirm  --aws-profile default
    - export CYPRESS_HOST=http://coolweb.s3-website-us-east-1.amazonaws.com
    - npm run cypress:run

  environment:
    name: staging
    url: http://coolweb.s3-website-us-east-1.amazonaws.com/ 